NewApp/Controllers/SaleController.cs
using CrystalDecisions.CrystalReports.Engine;
using NewApp.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.IO;
using System.Web.Mvc;

namespace NewApp.Controllers
{
    public class SaleController : SBaseController
    {
        #region Local variable declaration
        SqlConnection _Con;
        SqlCommand _Cmd;
        SqlDataAdapter _Ad;
        DataSet _DS = null;
        string username = string.Empty;
        string lastseen = string.Empty;
        string UserCode = string.Empty;
        int _PortalId = 0;
        int usertype = 0;
        public List<CardCodeBind> _CustomerList = new List<CardCodeBind>();
        public List<UserRegistrationDetails> _UserList = new List<UserRegistrationDetails>();
        #endregion

        #region Connection Method
        public void connection()
        {
            string constr = ConfigurationManager.ConnectionStrings["ConnectionString"].ToString();
            _Con = new SqlConnection(constr);
        }
        #endregion

        #region constructor

        public SaleController()
        {
            username = (string)System.Web.HttpContext.Current.Session["_SAP_ID"];
            lastseen = (string)System.Web.HttpContext.Current.Session["LastLoginDateTime"];
            UserCode = (string)System.Web.HttpContext.Current.Session["USER_CODE"];
            usertype = (int)System.Web.HttpContext.Current.Session["USER_TYPEID"];
        }
        #endregion

        #region Index
        public ActionResult Index()
        {
            try
            {
                if (UserCode == null || username == "")
                {
                    return Redirect("~/Default.aspx");
                }
                else
                {
                    int time = DateTime.Now.Hour;
                    if (time > 24)
                    {
                        time = 24;
                    }
                    if (time < 12)
                    {
                        ViewBag.UserName = "Good Morning : " + Session["F_NAME"].ToString();
                    }
                    else if (time < 17)
                    {
                        ViewBag.UserName = "Good Afternoon : " + Session["F_NAME"].ToString();
                    }
                    else
                    {
                        ViewBag.UserName = "Good Evening : " + Session["F_NAME"].ToString();
                    }
                    ViewBag.lastseen = "Last Login:" + Session["LastLoginDateTime"].ToString();
                    ViewBag.UserType = Session["USER_TYPEID"].ToString();
                    GetMovingValue();
                }
            }
            catch (Exception ex)
            {
                Response.Write(ex.Message);
            }
            return View();
        }
        public void GetMovingValue()
        {
            //string _SAPId,
            DataSet _Ds = null;
            try
            {
                _Ds = new DataSet();
                string _SAPID = username.ToString();
                List<Parameters> lstparameters = new List<Parameters>();
                lstparameters.Add(new Parameters("@SAPId", _SAPID));
                _Ds = dataAccess.GetDataSet("SP_GetMovingValue", lstparameters);
                if (_Ds.Tables[0].Rows.Count > 0)
                {
                    //string sVa = Convert.ToDecimal(_Ds.Tables[0].Rows[0].Field<decimal>("TotalOutstanding")).ToString();
                    ViewBag.TotalOut = Convert.ToDecimal(_Ds.Tables[0].Rows[0].Field<decimal>("TotalOutstanding")).ToString();
                    ViewBag.OverdueOut = Convert.ToDecimal(_Ds.Tables[0].Rows[0].Field<decimal>("OverdueOutstanding")).ToString();
                }

            }
            catch (Exception ex)
            {
                throw ex;
            }
        }
        #endregion

        #region Bind Value Then Customer Card Code Selectes
        [HttpPost]
        public JsonResult CustomerOnChange(string CardCode)
        {
            List<CardCode> _Mod = new List<CardCode>();
            connection();
            try
            {
                _Con.Open();
                _Cmd = new SqlCommand("POR_SP_Bind_HOME", _Con);
                _Cmd.CommandType = CommandType.StoredProcedure;
                _Cmd.Parameters.AddWithValue("@CardCode", (CardCode));
                _Ad = new SqlDataAdapter(_Cmd);
                DataSet _Ds;
                _Ds = new DataSet();
                _Ad.Fill(_Ds);
                foreach (DataRow _Dr in _Ds.Tables[0].Rows)
                {
                    _Mod.Add(new CardCode()
                    {
                        Address = _Dr["Address"].ToString(),
                        City = _Dr["City"].ToString(),
                        ZipCode = _Dr["ZipCode"].ToString(),
                        State1 = _Dr["State1"].ToString(),
                        Country = _Dr["Country"].ToString(),
                        Area = _Dr["Area"].ToString(),
                        Territory = _Dr["Territory"].ToString(),
                        SlpCode = _Dr["SlpCode"].ToString(),
                        CntctPrsn = _Dr["CntctPrsn"].ToString(),
                        Phone1 = _Dr["Phone1"].ToString(),
                        Fax = _Dr["Fax"].ToString(),
                        E_Mail = _Dr["E_Mail"].ToString(),
                        BalanceSys = _Dr["BalanceSys"].ToString(),
                        LastPaymentOn = _Dr["LastPaymentOn"].ToString(),
                        PAN = _Dr["PAN"].ToString(),
                        TIN = _Dr["TIN"].ToString(),
                        GSTINNo = _Dr["GSTINNo"].ToString(),
                        OverDueLess15 = _Dr["OverDueLess15"].ToString(),
                        OverDueGre15 = _Dr["OverDueGre15"].ToString(),
                        ExpPayment = _Dr["ExpPayment"].ToString(),
                        ordervalue = _Dr["ordervalue"].ToString(),
                        Shortfall = _Dr["Shortfall"].ToString(),
                        OverDueDays = _Dr["OverDueDays"].ToString(),
                        Warehouse = _Dr["Warehouse"].ToString(),
                        CreditLimit = _Dr["CreditLimit"].ToString(),
                        CreditDate = _Dr["CreditDate"].ToString(),
                        Consumed = _Dr["Consumed"].ToString(),
                        Order_Value = _Dr["Order_Value"].ToString(),
                        Limit = _Dr["Limit"].ToString(),
                        Total_Outstanding = _Dr["Total_Outstanding"].ToString(),
                        Available_Limit = _Dr["Available_Limit"].ToString(),
                        MaxOverduedays = _Dr["MAXOverDueDays"].ToString(),
                        Totaloverdue = _Dr["TotalOverDue"].ToString(),
                        Cerditbalance = _Dr["CREDITBALANCE"].ToString()
                    });
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            finally
            {
                _Con.Close();
                _Con.Dispose();
            }
            return Json(_Mod, JsonRequestBehavior.AllowGet);
        }
        [HttpPost]
        public JsonResult GetAllCustomerDdl(string _UserType)
        {
            //string _SAPId,
            DataSet _Ds = null;
            try
            {
                _Ds = new DataSet();
                List<Parameters> lstparameters = new List<Parameters>();
                lstparameters.Add(new Parameters("@UserType", _UserType.ToString()));
                _Ds = dataAccess.GetDataSet("SP_GetCustomer", lstparameters);
                foreach (DataRow _Dr in _Ds.Tables[0].Rows)
                {
                    _CustomerList.Add(new CardCodeBind()
                    {
                        CardCode = _Dr["CardCode"].ToString(),
                        CardName = _Dr["cardname"].ToString()
                    });
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(_CustomerList, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region OverDue Days
        [HttpPost]
        public JsonResult BindViewLessThanEqual15(string sCardCode)
        {
            try
            {
                _CustomerList.Clear();
                _DS = new DataSet();
                List<Parameters> lstparameters = new List<Parameters>();
                lstparameters.Add(new Parameters("@CARDCODE", sCardCode));
                _DS = dataAccess.GetDataSet("SP_PORTAL_OVECRDUELESS15", lstparameters);
                foreach (DataRow _Dr in _DS.Tables[0].Rows)
                {
                    _CustomerList.Add(new CardCodeBind()
                    {
                        DocNum_Less = _Dr["DocNum_Less"].ToString(),
                        DocDate_Less = _Dr["DocDate_Less"].ToString(),
                        DocDueDate_Less = _Dr["DocDueDate_Less"].ToString(),
                        Doctotal_Less = _Dr["Doctotal_Less"].ToString(),
                        BalancAmount_Less = _Dr["BalancAmount_Less"].ToString(),
                        DAYS_Less1 = _Dr["DAYS_Less1"].ToString()
                    });
                }
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return Json(new { draw = 1, recordsTotal = _CustomerList.Count, recordsFiltered = 10, data = _CustomerList }, JsonRequestBehavior.AllowGet);

            //return Json(_CustomerList, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult BindViewGreaterThan15(string sCardCode)
        {
            //string sCardCode = "C20000";
            try
            {
                _CustomerList.Clear();
                _DS = new DataSet();
                List<Parameters> lstparameters = new List<Parameters>();

NewApp/Views/Shared/_DashBoard.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-widthvar" />
    <title>Admin :: Home Page</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Cache-control" content="public">
    <script type="application/x-javascript">
        addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); }
    </script>
    <script type="text/javascript">
        function date_time(id) {
            date = new Date;
            year = date.getFullYear();
            month = date.getMonth();
            months = new Array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
            d = date.getDate();
            day = date.getDay();
            days = new Array('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday');
            h = date.getHours();
            if (h < 10) {
                h = "0" + h;
            }
            m = date.getMinutes();
            if (m < 10) {
                m = "0" + m;
            }
            s = date.getSeconds();
            if (s < 10) {
                s = "0" + s;
            }
            result = '' + days[day] + ' ' + months[month] + ' ' + d + ' ' + year + ' ' + h + ':' + m + ':' + s + ' ' + 'IST';
            document.getElementById(id).innerHTML = result;
            setTimeout('date_time("' + id + '");', '1000');
            return true;
        }
    </script>
    <style type="text/css">
        #date_time {
            margin-right: 10%;
            margin-top: 1%;
        }
    </style>
    <script type="text/javascript">
        //<![CDATA[</span />

        var clicked = false;
        function CheckBrowser() {
            if (clicked == false) {
                //Browser closed
            }
            else {
                //redirected
                clicked = false;
            }
        }

        function bodyUnload() {

            if (clicked == false)//browser is closed
            {
                var request = GetRequest();

                request.open("POST", "../LogOut.aspx", false);
                request.send();
            }
        }
        function GetRequest() {
            var xmlhttp;
            if (window.XMLHttpRequest) {// code for IE7+, Firefox, Chrome, Opera, Safari
                xmlhttp = new XMLHttpRequest();
            }
            else {// code for IE6, IE5
                xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
            }
            return xmlhttp;
        }
    </script>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/css/style.css" rel="stylesheet" />
    <!-- Nav CSS -->
    <link href="~/css/custom.css" rel="stylesheet" />
    <!-- Graph CSS -->
    <link href="~/css/lines.css" rel="stylesheet" />
    <link href="~/css/font-awesome.css" rel="stylesheet" />
    <!----webfonts--->
    <!-- jQuery -->
    <script src="~/js/jquery.min.js"></script>
    <link href='//fonts.googleapis.com/css?family=futura:400,100,300,500,700,900' rel='stylesheet' type='text/css' />
    <!---//webfonts--->
</head>
<body onunload="bodyUnload();" onclick="clicked=true;" style="background-color:#6ea1b9; font-family:'//fonts.googleapis.com/css?family=futura:400,100,300,500,700,900'">
    <div id="wrapper">
        <!-- Navigation -->
        <nav class="top1 navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0; height: auto; background-color: white; margin-top: -5px; left: 0; top: 0;">
            <div class="navbar-header" style="margin-top: -12px; padding-top: -11px;">
                <a class="navbar-brand" href="https://www.knauf.com/en/" target="_blank">
                    <img src="../icons/USG Knauf Logo.jpg" width="190" height="50" />
                </a>

            </div>
            <!-- /.navbar-header -->

            <div class="nav navbar-nav navbar-right">

                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle avatar" data-toggle="dropdown" />
                        @*<div class="label"/>
                                <span style="font-size: 10px; color: black;" id="date_time"></span>
                                <script type="text/javascript">
                                    window.onload = date_time('date_time');
                                </script>
                            </div>*@
                        <div class="label label-primary" style="background-color: #02AFF3 !important;">@ViewBag.UserName</div>
                    </li>
                    @if (System.Web.HttpContext.Current.Session["USER_CODE"].ToString() == "ADMIN")
                    {
                        <li>
                            @*<a href="~/UserChangePassword.aspx" /><span class="btn btn-xs btn-primary"><b>CHANGE PASSWORD</b></span>*@
                        </li>
                    }
                    else
                    {
                        <li>
                            <a href="~/UserChangePassword.aspx" /><span class="btn btn-xs btn-primary"><b>CHANGE PASSWORD</b></span>
                        </li>
                    }
                    <li>
                        <a href="~/LogOutPage.aspx" /><span class="label label-danger"><b>LOGOUT</b></span>
                    </li>
                </ul>
            </div>


            <div class="navbar-default sidebar" role="navigation" style="background-color:#6ea1b9;">

                <div class="sidebar-nav navbar-collapse" style="background-color:#6ea1b9;">

                    <ul class="nav" id="side-menu" style="background-color:#6ea1b9; color:white;">
                        @if (System.Web.HttpContext.Current.Session["USER_CODE"].ToString() == "ADMIN" || (int)System.Web.HttpContext.Current.Session["USER_TYPEID"] == 1)
                        {
                            <li>
                                <p><b style="color: white;">@ViewBag.lastseen</b></p>
                                <a href='@Url.Action("Home", "HomePage")' id="liHome"><i class="fa fa-home fa-fw nav_icon"></i><b style="color: white;">HOME</b></a>
                            </li>

                            <li>
                                <a><i class="fa fa-check-square-o nav_icon"></i><b style="color: white;">USER MANAGEMENT</b><span class="fa arrow" style="color: white;"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href='@Url.Action("UserReg", "UserRegistration")'><b style="color: white;">User Registration</b></a>
                                    </li>
                                    <li>
                                        <a href='@Url.Action("Index", "EnableDisable")'><b style="color: white;">Enable/Disable User</b></a>
                                    </li>
                                    <li>
                                        <a href="~/ManageUser.aspx"><b style="color: white;">Manage User</b></a>
                                    </li>

                                </ul>
                                <!-- /.nav-second-level -->
                            </li>
                            <li>
                                <a><i class="fa fa-cog fa-fw nav_icon"></i><b style="color:white;">SETTINGS</b><span class="fa arrow" style="color: white;"></span></a>
                                <ul class="nav nav-second-level">
                                    <li>
                                        <a href='@Url.Action("UserType", "HomePage")'><b style="color: white;">User Type</b></a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href='@Url.Action("Index", "LoginStatus")'><i class="fa fa-anchor fa-fw fa-lock" style="color:white;"></i><b style="color:white;">LOGIN STATUS</b></a>
                            </li>
                            <li>
                                <a href='@Url.Action("Index", "AuditLog")'><i class="fa fa-arrow-circle-o-left fa-fw fa-lock" style="color:white;"></i><b style="color:white;">AUDIT LOG</b></a>
                            </li>
                            <li>
                                <a href="~/LogOutPage.aspx"><i class="fa fa-lock fa-fw nav_icon"></i><b style="color:white;">LOGOUT</b></a>
                            </li>
                        }
                        else if (ViewBag.UserType == "2")
                        {
                        <li>
                            <p><b style="color: white;"> @ViewBag.lastseen </b></p>

                            <a href='@Url.Action("Index", "Sale")' id="liHome"><i class="fa fa-home fa-fw nav_icon"></i><b style="color:white;">HOME</b></a>
                        </li>
                        <li>
                            <a href="~/LogOutPage.aspx"><i class="fa fa-anchor fa-fw nav_icon"></i><b style="color:white;">LOGOUT</b></a>
                        </li>
                        }
                        else if (ViewBag.UserType == "3")
                        {
                        <li>
                            <p><b style="color: white;"> @ViewBag.lastseen </b></p>

                            <a href='@Url.Action("Index", "UserPage")' id="liHome"><i class="fa fa-home fa-fw nav_icon"></i><b style="color:white;">HOME</b></a>
                        </li>
                        <li>
                            <a href="~/LogOutPage.aspx"><i class="fa fa-anchor fa-fw nav_icon"></i><b style="color:white;">LOGOUT</b></a>
                        </li>
                        }
                        else
                        {
                        <li>
                            <p><b style="color: white;"> @ViewBag.lastseen </b></p>

                            <a href='@Url.Action("Index", "Manager")' id="liHome"><i class="fa fa-home fa-fw nav_icon"></i><b style="color:white;">HOME</b></a>
                        </li>
                        <li>
                            <a href="~/LogOutPage.aspx"><i class="fa fa-anchor fa-fw nav_icon"></i><b style="color:white;">LOGOUT</b></a>
                        </li>
                        }
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div>
            @RenderBody()
        </div>

        <!-- /#page-wrapper -->
        <div class="copy">
            <p></p>
        </div>
    </div>
    <!-- Bootstrap Core JavaScript -->

    <script src="~/js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/js/metisMenu.min.js"></script>
    <script src="~/js/custom.js"></script>
    <!-- Graph JavaScript -->
    <script src="~/js/d3.v3.js"></script>
    <script src="~/js/rickshaw.js"></script>
    @RenderSection("scripts", required: false)

</body>
</html>

NewApp/Views/Shared/_DashboardManager.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-widthvar" />
    <title>User :: Manager Home Page</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Cache-control" content="public">
    <script type="application/x-javascript">
     addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } 
    </script>
    <script type="text/javascript">
        function date_time(id) {
            date = new Date;
            year = date.getFullYear();
            month = date.getMonth();
            months = new Array('January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December');
            d = date.getDate();
            day = date.getDay();
            days = new Array('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday');
            h = date.getHours();
            if (h < 10) {
                h = "0" + h;
            }
            m = date.getMinutes();
            if (m < 10) {
                m = "0" + m;
            }
            s = date.getSeconds();
            if (s < 10) {
                s = "0" + s;
            }
            result = '' + days[day] + ' ' + months[month] + ' ' + d + ' ' + year + ' ' + h + ':' + m + ':' + s + ' ' + 'IST';
            document.getElementById(id).innerHTML = result;
            setTimeout('date_time("' + id + '");', '1000');
            return true;
        }
    </script>
    <style type="text/css">
        #date_time {
            margin-right: 10%;
            margin-top: 1%;
        }
    </style>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/css/style.css" rel="stylesheet" />
    <!-- Nav CSS -->
    <link href="~/css/custom.css" rel="stylesheet" />
    <!-- Graph CSS -->
    <link href="~/css/lines.css" rel="stylesheet" />
    <link href="~/css/font-awesome.css" rel="stylesheet" />
    <!----webfonts--->
    <!-- jQuery -->
    <script src="~/js/jquery.min.js"></script>
    <link href='//fonts.googleapis.com/css?family=Roboto:400,100,300,500,700,900' rel='stylesheet' type='text/css' />
    <!---//webfonts--->
</head>
<body>
    <div id="wrapper">
        <!-- Navigation -->
        <!-- /.navbar-header -->
        <nav class="top1 navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0; height: auto; background-color: white; margin-top: -5px; left: 0; top: 0;">
            <div class="navbar-header" style="margin-top: -12px; padding-top: -11px;">
                <a class="navbar-brand" href="https://www.usgboral.com/en_in/" target="_blank">@*USG BORAL*@
                    <img src="~/icons/rsz_usg_boral_logo.png" /></a>

            </div>
            <!-- /.navbar-header -->

            <div class="nav navbar-nav navbar-right">
                @*<span style="font-size: 14px; text-align: right; color: white;"  id="date_time"></span>
            <script type="text/javascript">
                window.onload = date_time('date_time');
            </script>*@
                <ul class="nav navbar-nav navbar-right">
                    @*<li class="dropdown">
                        <span class="label label-default"><label id="lblUserName" class="dropdown-toggle avatar" title="bbbbbbbbb">input text</label></span>
                    </li>*@
                    <li class="dropdown">
                        <a class="dropdown-toggle avatar" data-toggle="dropdown" />
                        <lable id="lblUserName" class="label label-primary">@ViewBag.UserName</lable>
                    </li>
                    <li class="dropdown">
                        <a href="~/LogOutPage.aspx" /><span class="label label-danger"><b>LOGOUT</b></span>
                    </li>
                </ul>
            </div>


            <div class="navbar-default sidebar" role="navigation">

                <div class="sidebar-nav navbar-collapse">
                    <ul class="nav" id="side-menu">
                        <li>
                            <p><b style="color: white;">@ViewBag.lastseen</b></p>
                            <a href='@Url.Action("Index", "Manager")' id="liHome"><i class="fa fa-home fa-fw nav_icon"></i><b>HOME</b></a>
                        </li>
                       
                        <li>
                            <a href="~/UserChangePassword.aspx" /><i class="fa fa-anchor fa-fw nav_icon"></i><b>CHANGE PASSWORD</b>
                        </li>
                        <li>
                            <a href="~/LogOutPage.aspx" /><i class="fa fa-anchor fa-fw nav_icon"></i><b>LOGOUT</b>
                            
                        </li>
                    </ul>
                </div>
                <!-- /.sidebar-collapse -->
            </div>
            <!-- /.navbar-static-side -->
        </nav>

        <div>
            @RenderBody()
        </div>

        <!-- /#page-wrapper -->
        <div class="copy">
            <p></p>
        </div>
    </div>
    <!-- Bootstrap Core JavaScript -->

    <script src="../js/bootstrap.min.js"></script>
    <!-- Metis Menu Plugin JavaScript -->
    <script src="~/js/metisMenu.min.js"></script>
    <script src="~/js/custom.js"></script>
    <!-- Graph JavaScript -->
    <script src="~/js/d3.v3.js"></script>
    <script src="~/js/rickshaw.js"></script>
    @RenderSection("scripts", required: false)

</body>
</html>

NewApp/Views/Shared/_LoaderImage.cshtml
<div style="display: none; position: absolute; top: 0; bottom: 0; left: 0; right: 0; z-index: 1000; background: rgba(0,0,0,0.5)" id="loader">
    <img alt="" src="~/fonts/ajax-loader-6.gif" style="top: 50%; left: 50%; position: absolute; text-align: center;" />
</div>

NewApp/Views/Shared/_LoaderPartial.cshtml
<div style="display: none; position: absolute; top: 0; bottom: 0; left: 0; right: 0; z-index: 1000; background: rgba(0,0,0,0.5)" id="loader">
    <img alt="" src="~/fonts/ajax-loader-6.gif" style="top: 50%; left: 50%; position: absolute; text-align: center;" />
</div>